project:
  type: website
  output-dir: docs

website:
  title: "shootmanng.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: slate
    css: styles.css
    toc: true

editor: visual

